server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://burnting.c02oobpyxopx.ap-northeast-2.rds.amazonaws.com/Burnting?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: duswjd0619
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update